In [134]:
import pandas as pd

df = pd.read_csv("C:/Users/DELL/Downloads/employees.csv")
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,NaN,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
# Create DataFrame
df = pd.DataFrame(df)

# Split email into username and domain, then create the username column
df['username'] = df['email'].str.split('@').str[0]

# Display the DataFrame
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,username
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,NaN,President,dmurphy
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales,mpatterso
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing,jfirrelli
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC),wpatterson
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA),gbondur
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA),abow
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep,ljennings
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep,lthompson
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep,jfirrelli
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep,spatterson
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep,ftseng
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep,gvanauf
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep,lbondur
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep,ghernande
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep,pcastillo
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep,lbott
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep,bjones
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep,afixter
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep,pmarsh
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep,tking
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep,mnishi
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep,ykato
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep,mgerard
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
# Define a dictionary mapping job titles to salaries
salary = {
    'President': 200000,
    'VP Sales': 150000,
    'VP Marketing': 150000,
    'Sales Manager (APAC)': 120000,
    'Sale Manager (EMEA)': 120000,
    'Sales Manager (NA)': 120000,
    'Sales Rep': 80000
}

# Map job titles to salaries and create a new salary column
df['salary'] = df['jobTitle'].map(salary)

# Display the DataFrame
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,username,salary
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,NaN,President,dmurphy,200000.0
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales,mpatterso,150000.0
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing,jfirrelli,150000.0
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC),wpatterson,120000.0
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA),gbondur,120000.0
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA),abow,120000.0
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep,ljennings,80000.0
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep,lthompson,80000.0
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep,jfirrelli,80000.0
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep,spatterson,80000.0
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep,ftseng,80000.0
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep,gvanauf,80000.0
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep,lbondur,80000.0
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep,ghernande,80000.0
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep,pcastillo,80000.0
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep,lbott,80000.0
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep,bjones,80000.0
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep,afixter,80000.0
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep,pmarsh,80000.0
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep,tking,80000.0
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep,mnishi,80000.0
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep,ykato,80000.0
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep,mgerard,80000.0
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
df = pd.DataFrame(df)


salaries = df[df['username'].isin(['mnishi', 'mgerard'])][['username', 'salary']]


print(salaries)

   username   salary
20   mnishi  80000.0
22  mgerard  80000.0

In [138]:
df = pd.DataFrame(df)


df['reportsTo'] = df['reportsTo'].fillna(method='bfill')


df

C:\Users\DELL\AppData\Local\Temp\ipykernel_7200\1238070169.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['reportsTo'] = df['reportsTo'].fillna(method='bfill')

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,username,salary
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,1002.0,President,dmurphy,200000.0
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales,mpatterso,150000.0
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing,jfirrelli,150000.0
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC),wpatterson,120000.0
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA),gbondur,120000.0
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA),abow,120000.0
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep,ljennings,80000.0
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep,lthompson,80000.0
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep,jfirrelli,80000.0
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep,spatterson,80000.0
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep,ftseng,80000.0
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep,gvanauf,80000.0
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep,lbondur,80000.0
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep,ghernande,80000.0
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep,pcastillo,80000.0
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep,lbott,80000.0
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep,bjones,80000.0
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep,afixter,80000.0
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep,pmarsh,80000.0
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep,tking,80000.0
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep,mnishi,80000.0
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep,ykato,80000.0
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep,mgerard,80000.0
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
df = pd.DataFrame(df)
mean_reportsTo = df['reportsTo'].mean()


# Display the mean
print(f"Mean of 'reportsTo': {mean_reportsTo}")

Mean of 'reportsTo': 1112.391304347826

In [140]:
df.describe()

       employeeNumber  officeCode    reportsTo         salary
count       25.000000   23.000000    23.000000      23.000000
mean      1310.880000    3.652174  1112.391304   96521.739130
std        230.378551    2.102135   119.851324   32137.304245
min       1002.000000    1.000000  1002.000000   80000.000000
25%       1102.000000    1.500000  1056.000000   80000.000000
50%       1286.000000    4.000000  1102.000000   80000.000000
75%       1504.000000    5.500000  1143.000000  100000.000000
max       1702.000000    7.000000  1621.000000  200000.000000

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   employeeNumber  25 non-null     int64
 1   lastName        24 non-null     object
 2   firstName       23 non-null     object
 3   extension       23 non-null     object
 4   email           23 non-null     object
 5   officeCode      23 non-null     float64
 6   reportsTo       23 non-null     float64
 7   jobTitle        23 non-null     object
 8   username        23 non-null     object
 9   salary          23 non-null     float64
dtypes: float64(3), int64(1), object(6)
memory usage: 2.1+ KB

In [142]:
df.isnull().sum()

employeeNumber    0
lastName          1
firstName         2
extension         2
email             2
officeCode        2
reportsTo         2
jobTitle          2
username          2
salary            2
dtype: int64

In [143]:
df.head(3)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,username,salary
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,1002.0,President,dmurphy,200000.0
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales,mpatterso,150000.0
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing,jfirrelli,150000.0

In [144]:
print(df["employeeNumber"].duplicated().sum())
df

2

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,username,salary
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,1002.0,President,dmurphy,200000.0
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales,mpatterso,150000.0
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing,jfirrelli,150000.0
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC),wpatterson,120000.0
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA),gbondur,120000.0
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA),abow,120000.0
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep,ljennings,80000.0
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep,lthompson,80000.0
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep,jfirrelli,80000.0
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep,spatterson,80000.0
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep,ftseng,80000.0
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep,gvanauf,80000.0
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep,lbondur,80000.0
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep,ghernande,80000.0
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep,pcastillo,80000.0
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep,lbott,80000.0
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep,bjones,80000.0
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep,afixter,80000.0
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep,pmarsh,80000.0
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep,tking,80000.0
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep,mnishi,80000.0
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep,ykato,80000.0
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep,mgerard,80000.0
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
df.drop_duplicates("employeeNumber")

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,username,salary
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,1002.0,President,dmurphy,200000.0
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales,mpatterso,150000.0
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing,jfirrelli,150000.0
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC),wpatterson,120000.0
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA),gbondur,120000.0
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA),abow,120000.0
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep,ljennings,80000.0
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep,lthompson,80000.0
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep,jfirrelli,80000.0
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep,spatterson,80000.0
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep,ftseng,80000.0
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep,gvanauf,80000.0
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep,lbondur,80000.0
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep,ghernande,80000.0
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep,pcastillo,80000.0
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep,lbott,80000.0
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep,bjones,80000.0
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep,afixter,80000.0
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep,pmarsh,80000.0
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep,tking,80000.0
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep,mnishi,80000.0
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep,ykato,80000.0
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep,mgerard,80000.0

In [146]:
import pandas as pd

df = pd.read_csv("C:/Users/DELL/Downloads/employees.csv")
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,NaN,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [147]:
df.isnull().sum()
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,NaN,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [148]:
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,NaN,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
import numpy as np
df.replace(np.nan,"Qaaamar")

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,Qaaamar,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep
23,1002,Murphy,Qaaamar,Qaaamar,Qaaamar,Qaaamar,Qaaamar,Qaaamar
24,1056,Qaaamar,Qaaamar,Qaaamar,Qaaamar,Qaaamar,Qaaamar,Qaaamar

In [150]:
df["officeCode"]=df["officeCode"].replace(np.nan,27.36)

print(df["officeCode"].mean())
df

5.5488

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.00,NaN,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.00,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.00,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.00,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.00,1056.0,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.00,1056.0,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.00,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.00,1143.0,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.00,1143.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.00,1143.0,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.00,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.00,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.00,1102.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.00,1102.0,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.00,1102.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.00,1102.0,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.00,1102.0,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.00,1088.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.00,1088.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.00,1088.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.00,1056.0,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.00,1621.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.00,1102.0,Sales Rep
23,1002,Murphy,NaN,NaN,NaN,27.36,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,27.36,NaN,NaN

In [151]:
import pandas as pd

df = pd.read_csv("C:/Users/DELL/Downloads/employees.csv")
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,NaN,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [152]:
df.fillna(method="ffill")
df

C:\Users\DELL\AppData\Local\Temp\ipykernel_7200\1737168024.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,NaN,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [153]:
import pandas as pd

Data = pd.read_csv("C:/Users/DELL/Downloads/employees.csv")
Data

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1.0,NaN,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1.0,1002.0,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1.0,1002.0,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6.0,1056.0,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4.0,1056.0,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1.0,1056.0,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1.0,1143.0,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1.0,1143.0,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2.0,1143.0,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2.0,1143.0,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3.0,1143.0,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3.0,1143.0,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4.0,1102.0,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4.0,1102.0,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4.0,1102.0,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7.0,1102.0,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7.0,1102.0,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6.0,1088.0,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6.0,1088.0,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6.0,1088.0,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5.0,1056.0,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5.0,1621.0,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4.0,1102.0,Sales Rep
23,1002,Murphy,NaN,NaN,NaN,NaN,NaN,NaN
24,1056,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
import pandas as pd

# Sample data
data = {
    'employeeNumber': [1002, 1056, 1076, 1088, 1102, 1143, 1165, 1166, 1188, 1216, 1286, 1323, 1337, 1370, 1401, 1501, 1504, 1611, 1612, 1619, 1621, 1625, 1702],
    'lastName': ['Murphy', 'Patterson', 'Firrelli', 'Patterson', 'Bondur', 'Bow', 'Jennings', 'Thompson', 'Firrelli', 'Patterson', 'Tseng', 'Vanauf', 'Bondur', 'Hernandez', 'Castillo', 'Bott', 'Jones', 'Fixter', 'Marsh', 'King', 'Nishi', 'Kato', 'Gerard'],
    'firstName': ['Diane', 'Mary', 'Jeff', 'William', 'Gerard', 'Anthony', 'Leslie', 'Leslie', 'Julie', 'Steve', 'Foon Yue', 'George', 'Loui', 'Gerard', 'Pamela', 'Larry', 'Barry', 'Andy', 'Peter', 'Tom', 'Mami', 'Yoshimi', 'Martin'],
    'extension': ['x5800', 'x4611', 'x9273', 'x4871', 'x5408', 'x5428', 'x3291', 'x4065', 'x2173', 'x4334', 'x2248', 'x4102', 'x6493', 'x2028', 'x2759', 'x2311', 'x102', 'x101', 'x102', 'x103', 'x101', 'x102', 'x2312'],
    'email': ['dmurphy@classicmodelcars.com', 'mpatterso@classicmodelcars.com', 'jfirrelli@classicmodelcars.com', 'wpatterson@classicmodelcars.com', 'gbondur@classicmodelcars.com', 'abow@classicmodelcars.com', 'ljennings@classicmodelcars.com', 'lthompson@classicmodelcars.com', 'jfirrelli@classicmodelcars.com', 'spatterson@classicmodelcars.com', 'ftseng@classicmodelcars.com', 'gvanauf@classicmodelcars.com', 'lbondur@classicmodelcars.com', 'ghernande@classicmodelcars.com', 'pcastillo@classicmodelcars.com', 'lbott@classicmodelcars.com', 'bjones@classicmodelcars.com', 'afixter@classicmodelcars.com', 'pmarsh@classicmodelcars.com', 'tking@classicmodelcars.com', 'mnishi@classicmodelcars.com', 'ykato@classicmodelcars.com', 'mgerard@classicmodelcars.com'],
    'officeCode': [1, 1, 1, 6, 4, 1, 1, 1, 2, 2, 3, 3, 4, 4, 4, 7, 7, 6, 6, 6, 5, 5, 4],
    'reportsTo': [None, 1002, 1002, 1056, 1056, 1056, 1143, 1143, 1143, 1143, 1143, 1143, 1102, 1102, 1102, 1102, 1102, 1088, 1088, 1088, 1056, 1621, 1102],
    'jobTitle': ['President', 'VP Sales', 'VP Marketing', 'Sales Manager (APAC)', 'Sale Manager (EMEA)', 'Sales Manager (NA)', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep']
}

# Create DataFrame
df = pd.DataFrame(data)

# Add a new column 'bonus' with dummy data
df['bonus'] = [5000, 4000, 4000, 3000, 3000, 3000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 1500, 1500, 1000, 1000, 1000, 500, 500, 500]

# Display the updated DataFrame
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,bonus
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,NaN,President,5000
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002.0,VP Sales,4000
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002.0,VP Marketing,4000
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056.0,Sales Manager (APAC),3000
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056.0,Sale Manager (EMEA),3000
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056.0,Sales Manager (NA),3000
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep,2000
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143.0,Sales Rep,2000
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143.0,Sales Rep,2000
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep,2000
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143.0,Sales Rep,2000
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143.0,Sales Rep,2000
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102.0,Sales Rep,2000
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep,2000
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102.0,Sales Rep,2000
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,1500
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102.0,Sales Rep,1500
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088.0,Sales Rep,1000
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088.0,Sales Rep,1000
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088.0,Sales Rep,1000
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056.0,Sales Rep,500
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621.0,Sales Rep,500
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102.0,Sales Rep,500

In [155]:
import pandas as pd

# Sample data
data = {
    'employeeNumber': [1002, 1056, 1076, 1088, 1102, 1143, 1165, 1166, 1188, 1216, 1286, 1323, 1337, 1370, 1401, 1501, 1504, 1611, 1612, 1619, 1621, 1625, 1702],
    'lastName': ['Murphy', 'Patterson', 'Firrelli', 'Patterson', 'Bondur', 'Bow', 'Jennings', 'Thompson', 'Firrelli', 'Patterson', 'Tseng', 'Vanauf', 'Bondur', 'Hernandez', 'Castillo', 'Bott', 'Jones', 'Fixter', 'Marsh', 'King', 'Nishi', 'Kato', 'Gerard'],
    'firstName': ['Diane', 'Mary', 'Jeff', 'William', 'Gerard', 'Anthony', 'Leslie', 'Leslie', 'Julie', 'Steve', 'Foon Yue', 'George', 'Loui', 'Gerard', 'Pamela', 'Larry', 'Barry', 'Andy', 'Peter', 'Tom', 'Mami', 'Yoshimi', 'Martin'],
    'extension': ['x5800', 'x4611', 'x9273', 'x4871', 'x5408', 'x5428', 'x3291', 'x4065', 'x2173', 'x4334', 'x2248', 'x4102', 'x6493', 'x2028', 'x2759', 'x2311', 'x102', 'x101', 'x102', 'x103', 'x101', 'x102', 'x2312'],
    'email': ['dmurphy@classicmodelcars.com', 'mpatterso@classicmodelcars.com', 'jfirrelli@classicmodelcars.com', 'wpatterson@classicmodelcars.com', 'gbondur@classicmodelcars.com', 'abow@classicmodelcars.com', 'ljennings@classicmodelcars.com', 'lthompson@classicmodelcars.com', 'jfirrelli@classicmodelcars.com', 'spatterson@classicmodelcars.com', 'ftseng@classicmodelcars.com', 'gvanauf@classicmodelcars.com', 'lbondur@classicmodelcars.com', 'ghernande@classicmodelcars.com', 'pcastillo@classicmodelcars.com', 'lbott@classicmodelcars.com', 'bjones@classicmodelcars.com', 'afixter@classicmodelcars.com', 'pmarsh@classicmodelcars.com', 'tking@classicmodelcars.com', 'mnishi@classicmodelcars.com', 'ykato@classicmodelcars.com', 'mgerard@classicmodelcars.com'],
    'officeCode': [1, 1, 1, 6, 4, 1, 1, 1, 2, 2, 3, 3, 4, 4, 4, 7, 7, 6, 6, 6, 5, 5, 4],
    'reportsTo': [None, 1002, 1002, 1056, 1056, 1056, 1143, 1143, 1143, 1143, 1143, 1143, 1102, 1102, 1102, 1102, 1102, 1088, 1088, 1088, 1056, 1621, 1102],

    'jobTitle': ['President', 'VP Sales', 'VP Marketing', 'Sales Manager (APAC)', 'Sale Manager (EMEA)', 'Sales Manager (NA)', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep']
}




# Create DataFrame
df = pd.DataFrame(data)

# Add a new column 'bonus' with dummy data
df['bonus'] = [5000, 4000, 4000, 3000, 3000, 3000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 1500, 1500, 1000, 1000, 1000, 500, 500, 500]

# Create 'GetBonus' column based on the 'bonus' column
df['GetBonus'] = np.where(df['bonus'] == 0, 'no bonus', 'bonus')

# Display the updated DataFrame
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,bonus,GetBonus
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,NaN,President,5000,bonus
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002.0,VP Sales,4000,bonus
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002.0,VP Marketing,4000,bonus
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056.0,Sales Manager (APAC),3000,bonus
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056.0,Sale Manager (EMEA),3000,bonus
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056.0,Sales Manager (NA),3000,bonus
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep,2000,bonus
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143.0,Sales Rep,2000,bonus
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143.0,Sales Rep,2000,bonus
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep,2000,bonus
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143.0,Sales Rep,2000,bonus
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143.0,Sales Rep,2000,bonus
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102.0,Sales Rep,2000,bonus
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep,2000,bonus
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102.0,Sales Rep,2000,bonus
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,1500,bonus
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102.0,Sales Rep,1500,bonus
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088.0,Sales Rep,1000,bonus
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088.0,Sales Rep,1000,bonus
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088.0,Sales Rep,1000,bonus
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056.0,Sales Rep,500,bonus
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621.0,Sales Rep,500,bonus
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102.0,Sales Rep,500,bonus

In [156]:
import pandas as pd

# Sample data
data = {
    'employeeNumber': [1002, 1056, 1076, 1088, 1102, 1143, 1165, 1166, 1188, 1216, 1286, 1323, 1337, 1370, 1401, 1501, 1504, 1611, 1612, 1619, 1621, 1625, 1702],
    'lastName': ['Murphy', 'Patterson', 'Firrelli', 'Patterson', 'Bondur', 'Bow', 'Jennings', 'Thompson', 'Firrelli', 'Patterson', 'Tseng', 'Vanauf', 'Bondur', 'Hernandez', 'Castillo', 'Bott', 'Jones', 'Fixter', 'Marsh', 'King', 'Nishi', 'Kato', 'Gerard'],
    'firstName': ['Diane', 'Mary', 'Jeff', 'William', 'Gerard', 'Anthony', 'Leslie', 'Leslie', 'Julie', 'Steve', 'Foon Yue', 'George', 'Loui', 'Gerard', 'Pamela', 'Larry', 'Barry', 'Andy', 'Peter', 'Tom', 'Mami', 'Yoshimi', 'Martin'],
    'extension': ['x5800', 'x4611', 'x9273', 'x4871', 'x5408', 'x5428', 'x3291', 'x4065', 'x2173', 'x4334', 'x2248', 'x4102', 'x6493', 'x2028', 'x2759', 'x2311', 'x102', 'x101', 'x102', 'x103', 'x101', 'x102', 'x2312'],
    'email': ['dmurphy@classicmodelcars.com', 'mpatterso@classicmodelcars.com', 'jfirrelli@classicmodelcars.com', 'wpatterson@classicmodelcars.com', 'gbondur@classicmodelcars.com', 'abow@classicmodelcars.com', 'ljennings@classicmodelcars.com', 'lthompson@classicmodelcars.com', 'jfirrelli@classicmodelcars.com', 'spatterson@classicmodelcars.com', 'ftseng@classicmodelcars.com', 'gvanauf@classicmodelcars.com', 'lbondur@classicmodelcars.com', 'ghernande@classicmodelcars.com', 'pcastillo@classicmodelcars.com', 'lbott@classicmodelcars.com', 'bjones@classicmodelcars.com', 'afixter@classicmodelcars.com', 'pmarsh@classicmodelcars.com', 'tking@classicmodelcars.com', 'mnishi@classicmodelcars.com', 'ykato@classicmodelcars.com', 'mgerard@classicmodelcars.com'],
    'officeCode': [1, 1, 1, 6, 4, 1, 1, 1, 2, 2, 3, 3, 4, 4, 4, 7, 7, 6, 6, 6, 5, 5, 4],
    'reportsTo': [None, 1002, 1002, 1056, 1056, 1056, 1143, 1143, 1143, 1143, 1143, 1143, 1102, 1102, 1102, 1102, 1102, 1088, 1088, 1088, 1056, 1621, 1102],
    'jobTitle': ['President', 'VP Sales', 'VP Marketing', 'Sales Manager (APAC)', 'Sale Manager (EMEA)', 'Sales Manager (NA)', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep', 'Sales Rep'],
    'Salary': [5000, 4000, 4000, 3000, 3000, 3000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 1500, 1500, 1000, 1000, 1000, 500, 500, 500],
}

# Create DataFrame


# Display the DataFrame
df

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle,bonus,GetBonus
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,NaN,President,5000,bonus
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002.0,VP Sales,4000,bonus
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002.0,VP Marketing,4000,bonus
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056.0,Sales Manager (APAC),3000,bonus
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056.0,Sale Manager (EMEA),3000,bonus
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056.0,Sales Manager (NA),3000,bonus
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143.0,Sales Rep,2000,bonus
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143.0,Sales Rep,2000,bonus
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143.0,Sales Rep,2000,bonus
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143.0,Sales Rep,2000,bonus
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143.0,Sales Rep,2000,bonus
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143.0,Sales Rep,2000,bonus
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102.0,Sales Rep,2000,bonus
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102.0,Sales Rep,2000,bonus
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102.0,Sales Rep,2000,bonus
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102.0,Sales Rep,1500,bonus
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102.0,Sales Rep,1500,bonus
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088.0,Sales Rep,1000,bonus
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088.0,Sales Rep,1000,bonus
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088.0,Sales Rep,1000,bonus
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056.0,Sales Rep,500,bonus
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621.0,Sales Rep,500,bonus
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102.0,Sales Rep,500,bonus

In [157]:
# Define a dictionary mapping job titles to salaries
salary = {
    'President': 200000,
    'VP Sales': 150000,
    'VP Marketing': 150000,
    'Sales Manager (APAC)': 120000,
    'Sale Manager (EMEA)': 120000,
    'Sales Manager (NA)': 120000,
    'Sales Rep': 80000
}

# Map job titles to salaries and create a new salary column
df['salary'] = df['jobTitle'].map(salary)

# Display the DataFrame
df


Data["Bonus"]=(df["Salary"]/100)*20
Data

KeyError: 'Salary'